name: "PROD GUILHERME"


on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: " " //pegar o roles e pesquisar pelo github actions
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: " " //pegar o nome do bucket S3
      aws-lock-dynamodb-table: " " //pega o nome da primeira tabela criada
