version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_conhecimentos
    restart: always
    environment:
      MYSQL_DATABASE: conhecimentos
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

  app:
    build: .
    container_name: springboot_conhecimentos
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/conhecimentos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - spring-net

volumes:
  mysql_data:

networks:
  spring-net:
    driver: bridge
